# Generated by Django 5.2.3 on 2025-07-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_useranswer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Номер попытки"),
        ),
    ]
