# Generated by Django 5.2.3 on 2025-07-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_useranswer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название теста"),
        ),
    ]
