# Generated by Django 5.2.3 on 2025-07-02 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_alter_assessment_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="answered_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа"),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("user", "question", "attempt_number"), name="unique_attempt_per_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)), fields=("user", "question"), name="unique_correct_answer"
            ),
        ),
    ]
